### ISSUE TITLE
report page broken

### ISSUE THREAD

**Issue by Kennric** [osuosl/iam#165]

**Comment by alxngyn** [comment]
works locally
![download 4](https://cloud.githubusercontent.com/assets/7299081/20070453/413be57c-a4d5-11e6-8851-c6f6b9507825.png)

also, iam-staging.osuosl.org is down at the moment

**Comment by alxngyn** [comment]
since we poll the nodes for their disktemplate like any other plugin we get a report structure like:
`[{:id=>22, :node_resource=>1, :created=>2016-10-27 20:59:18 +0000, :node=>"config.drupal.org", :value=>"drbd", :active=>true}, 
{:id=>175, :node_resource=>1, :created=>2016-10-27 21:26:21 +0000, :node=>"config.drupal.org", :value=>"drbd", :active=>true}, ... ]` 
For the edge case of a nodeResource exists but the plugin hasn't stored any data yet the report page breaks because data is an empty list.
```
data  = []
data [0] = nil  # !!!
```
