### ISSUE TITLE
Convert Redis to PostgreSQL h_store (or the JSON store)

### ISSUE THREAD

**Issue by Kennric** [osuosl/iam#47]
convert current Redis code to use postgres h_store instead

**Comment by ElijahCaine** [comment]
I'd like to do this to get finally get my hands dirty with some ruby code.

**Comment by matthewrsj** [comment]
@ElijahCaine 
@Kennric and I were talking about the JSON data type instead of the hstore data type because it allows nested fields.

**Comment by alxngyn** [comment]
I know we talked about this, but since we're moving away from the key store data type is the DB fields now: 
```
cache_table
    timestamp,  time
    the-giant-nested-data-from-ganetti, json 
```
or (each db field matches with a field/key from ganetti's json)

```
cache_table
    timestamp time
    disk_usage, 	 int
    oper_vcpus, 	 int
    serial_no, 	 int
    ctime, 	 float
    hvparams, 	 json
    oper_state, 	 boolean
    disk_template, 	 String
    mtime, 	 float
    nic.modes, 	 text[]
    oper_ram, 	 int
    pnode, 	 String
    nic.bridges, 	 text[]
    status, 	 String
    custom_hvparams, 	 json
    tags, 	 text[]
    snodes, 	 text[]
    nic.macs, 	 text[]
    nic.ips, 	 text[]
    network_port, 	 int
    name, 	 String
    custom_beparams, 	 json
    custom_nicparams, 	 text[]
    uuid, 	 String
    disk.sizes, 	 text[]
    admin_state, 	 String
    nic.links, 	 text[]
    os, 	 String
    beparams, 	 json
```
(I got the parsed the fields with a little ruby script here: https://github.com/osuosl/iam/blob/alxngyn/json-postgres-test/psql_json_test.rb)

I know we wanted to parse some data so in the future we can utilize plugins to store/process them

**Comment by ElijahCaine** [comment]
@alxngyn We should be explicit and set  cache_table closer to the second option. It's easier for that to be self documented imo.

**Comment by matthewrsj** [comment]
@alxngyn and I had a discussion about this today.

Basically, there are several problems with using the PG hstore or JSON data types. 

General problems
-----------------

* They are just *data types* for key value storage, so we need models and schema to create our cache table.
* They belong in a DB table, which means that simply dumping data won't work, since it will just add data instead of overwriting old data. Because of this we must make sure we *update* the correct old data so our cache doesn't get too large. We also need to do checks on a datetime associated with the node when updating.
* We need to store different types of data (nodes, db, bandwidth, etc.). We discussed storing each of these under a key <resource>_data (i.e. node_data, db_data, etc.). That means we would have to update *entire nested rows* of data every time we update one node_data fqdn. Another option is storing everything in its own table...

hstore specifically
-------------------

* Doesn't allow nested key/value storage. This isn't really an option because of this.

Conclusion
----------

With all of those issues above, we still need to manipulate the data before caching so it is in a standardized structure. We then store it in the DB using very specific models and schema. Then we pull it out of the DB, format it some more, then put it back in the DB somewhere else. Why?

Proposed Solution
-----------------

Redis fits our needs perfectly. We dump the data into a KV store in a usable template, then pull it out, process and place in long term storage. I understand it causes a small headache for our systems guys, but using hstore or JSON data types seems like a huge complexity for very little benefit. I suggest we discuss the possibility of remaining with redis long-term.

**Comment by alxngyn** [comment]
+1
Also, we're going to need the whole DB setup of data models, migration files, db cleanup, etc ...
I feel like all that work is redundant to our plugin architecture.

Is it possible to piggy back redis onto an existing VM somewhere on the network? Maybe have Redis run on the same box as the ruby app?

**Comment by ElijahCaine** [comment]
I wasn't part of the conversation with @matthewrsj and @alxngyn. That said I think there are a few advantages to at least *trying* the PostgreSQL JSON store:

- We already have a workflow for deploying PostgreSQL databases. We have never deployed Redis. I'm not going to say Redis is *impossible* to deploy but in my experience deploying new tools is a *lot* more work than we expect. We should only use Redis if no other option exist that fits the bill.
- Formalizing the data we store in our cache (whichever one we choose) will help writing plugins in that the plugin just needs to do a lookup for `[field_name]` on a given host and doesn't need to know `[ohai_field_name]` is roughly equivalent to `[rapi_field_name]` not to be confused with `[similar_rapi_field_name]`.
- To specifically address @matthewrsj's last two points, they honestly seem like trivial programming problems. In our `collect` code we grab data from the API, format it correctly in JSON, and overwrite the old cache. Storing everything in a different table also doesn't seem too difficult. I might be entirely under-informed but these seem like solvable problems. It's *less convenient* than grabbing JSON from an API and dumping it into Redis, but by no means does it sound impossible.

I'm not saying Redis is the wrong tool for the job but I need at least be the devil's advocate on this. It might be easy to keep using Redis but that doesn't mean it won't bite us later.

**Comment by matthewrsj** [comment]
I think the biggest issue is what @alxngyn said:
> Also, we're going to need the whole DB setup of data models, migration files, db cleanup, etc ...
I feel like all that work is redundant to our plugin architecture.

@ElijahCaine re: point 2. If we use a cache, we will be formalizing the data. Whether we use redis or pg.

I'm not advocating that we *don't* use a cache. I just don't see the benefit of using a tool that makes our lives more difficult. I understand the argument about the difficulty in deploying new tools, that's what this conversation is about. 

Personally, I think deploying redis once makes IAM much easier to write since caching is so much easier with redis. That being said, I probably won't be the one who ends up with the headache of deploying redis...

**If** we decide against redis, I'm not convinced we should be caching at all. Instead of trying to cache in a DB table, I'd rather just have the plugins call the appropriate collector (or vice versa), which will then return the formatted data to the plugin. The plugin would then just put it in the DB in the correct place, formatted correctly. I would rather cache with redis TBH.

**Comment by ElijahCaine** [comment]
I would still like to *explore the option* of using Postgres to do Redis' job.

**Comment by matthewrsj** [comment]
@ElijahCaine +1

**Comment by jldugger** [comment]
So it sounds like Redis serves two major purposes here:

1. cache a fairly large API response from a fairly slow backend
2. easily query hierarchial data within that API response

1 seems pretty simple to do with memcached, varnish, or depending on the application structure, a local variable. 2 seems like the value Redis is adding. I really don't know enough about the problem space to make a judgment about whether doing 2 in the app is feasible, or worth the additional complications.

What I will say is that Redis is a new service for the OSL. As far as the headaches go, it could be easy, or could be quite hard. The distribution of outcomes is quite wide at this point. It's not something we've deployed before. Before Operations can support a Redis service for something as important as billing clients, we'd need to take several steps:

- [ ] identify a chef cookbook to deploy and manage Redis on CentOS
- [ ] potentially address issues with the cookbook
- [ ] identify a location to deploy Redis to
- [ ] Nagios checks for Redis availability
- [ ] documentation on Redis's architecture, Redis user management available, and any other common administrative tasks

**Comment by matthewrsj** [comment]
@jldugger Why memcached or varnish over redis? Have we deployed these before? Memcached looks promising, but I haven't looked into it much. 

If we *do* decide to go with redis, I would be interested in working through the deployment with help from infra (but I will be gone for the summer, so that is a bit of an empty offer).

**Comment by jldugger** [comment]
@matthewrsj We have deployed both memcached and varnish before. We heavily use varnish in other parts of our infrastructure, though I don't know if we actually have that in chef yet. But we know the theory of operation well, and existing HTTP checks would establish reliability.

But these merely provide caching mechanisms. For Varnish, you'd define Ganeti REST API as a backend, and set a cache timeout rule, then GETs would be transparently cached. In the case of memcached, the cache is updated with POST and requested with GET. In both cases, any hierarchial processing is done client side.

Which means the query API use case isn't solved by these any more than hstore solves it. Reviewing `develop` branch didn't make it clear to me exactly which queries were being sent to redis, so I can't really say if there's a Ruby gem that provides similar queries to JSON objects.

**Comment by Kennric** [comment]
@matthewrsj, @jldugger If memcached is more easily deployable/maintainable/available than Redis, I believe we could use it in very much the same way we use Redis now, via a ruby memcache gem. 

I think varnish would be an option for @ElijahCaine 's idea of having the plugins call collectors without an application level cache, which would amount to calling the ganeti api over and over - however, I am not sure how it would work for our database data collection plugins, or other things that are not http based.

One possible ruby memcache gem: https://github.com/ninjudd/memcache

**Comment by Kennric** [comment]
One nice benefit of memcache is a built-in expiry mechanism. One possible issue is object size constraints.

**Comment by ElijahCaine** [comment]
If @jldugger doesn't have any problems with us using memcache on the ops side it's looking like that is our best (non-redis) option with minimal refactors to the code we have thus-far.

**Comment by ElijahCaine** [comment]
Deprecated by issue #94
